# Generated by Django 6.0 on 2025-12-30 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_song_bookmarked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('name', models.CharField(default='default', max_length=32, primary_key=True, serialize=False)),
                ('font_weight', models.CharField(blank=True, default='normal', max_length=10)),
                ('font_style', models.CharField(blank=True, default='normal', max_length=32)),
                ('src', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('name', models.CharField(default='default', max_length=128, primary_key=True, serialize=False)),
                ('bg_main', models.CharField(default='#0A0A0A', max_length=128)),
                ('bg_nav', models.CharField(default='#121212', max_length=128)),
                ('bg_sidebar', models.CharField(default='#1A1A1A', max_length=128)),
                ('bg_sidebar_selection', models.CharField(default='#333333', max_length=128)),
                ('bg_sidebar_hover', models.CharField(default='#222222', max_length=128)),
                ('bg_content_blend', models.CharField(default='#0A0A0AC0', max_length=128)),
                ('bg_content', models.CharField(default='#0f0f0f', max_length=128)),
                ('text_color', models.CharField(default='#ffffff', max_length=128)),
                ('link_color', models.CharField(default='#cccccc', max_length=128)),
                ('accent_color', models.CharField(default='#ffa340', max_length=128)),
                ('secondary_color', models.CharField(default='#888888', max_length=128)),
                ('section_color', models.CharField(default='#eeeeee', max_length=128)),
                ('confirm_color', models.CharField(default='#dddddd', max_length=128)),
                ('bg_player_title', models.CharField(default='#2a2a2a', max_length=128)),
                ('shadow_color', models.CharField(default='#000000', max_length=128)),
                ('tile_placeholder', models.CharField(default='#333333', max_length=128)),
                ('tile_info', models.CharField(default='#050505', max_length=128)),
                ('tile_info_text', models.CharField(default='#666666', max_length=128)),
                ('gradient_begin', models.CharField(default='#444444', max_length=128)),
                ('gradient_end', models.CharField(default='#111111', max_length=128)),
                ('nav_height', models.CharField(default='60px', max_length=32)),
                ('sidebar_width', models.CharField(default='432px', max_length=32)),
                ('default_font', models.CharField(default="'lunchtype-regular'", max_length=32)),
                ('player_font', models.CharField(default="'lunchtype-regular'", max_length=32)),
                ('player_font_size', models.CharField(default='24px', max_length=32)),
                ('renderer', models.CharField(default='themed', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='main.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='main.genre'),
        ),
        migrations.CreateModel(
            name='NostrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.CharField(help_text='Public key en formato hex', max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nostr_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
