# Generated by Django 6.0 on 2025-12-24 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.CharField(blank=True, max_length=300)),
                ('bio', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('genres', models.ManyToManyField(blank=True, to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('codename', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('brief', models.TextField(blank=True)),
                ('picture', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('booklet', models.FileField(blank=True, null=True, upload_to='booklets/')),
                ('edition', models.CharField(blank=True, default='Vanila', max_length=200)),
                ('limited', models.BooleanField(default=False)),
                ('release', models.DateField(blank=True, null=True)),
                ('artists', models.ManyToManyField(blank=True, to='main.artist')),
                ('genres', models.ManyToManyField(blank=True, to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=200)),
                ('filename', models.CharField(default='untitled.mp3', max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('track_number', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('lyrics', models.TextField(blank=True)),
                ('picture', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('times_played', models.PositiveIntegerField(default=0)),
                ('times_skipped', models.PositiveIntegerField(default=0)),
                ('bookmarked', models.BooleanField(default=False)),
                ('codename', models.CharField(blank=True, max_length=200)),
                ('error', models.BooleanField(default=False)),
                ('errors', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, default=1, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=128)),
                ('bpm', models.FloatField(blank=True, null=True)),
                ('tone', models.CharField(blank=True, max_length=50)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.genre')),
                ('tags', models.ManyToManyField(blank=True, to='main.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='playlists/')),
                ('artists', models.ManyToManyField(blank=True, to='main.artist')),
                ('genres', models.ManyToManyField(blank=True, to='main.genre')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, to='main.song')),
            ],
        ),
    ]
