# Generated by Django 6.0 on 2025-12-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='bookmarked',
        ),
    ]
