# Generated by Django 6.0 on 2026-05-29 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('name', models.CharField(default='default', max_length=32, primary_key=True, serialize=False)),
                ('font_weight', models.CharField(blank=True, default='normal', max_length=10)),
                ('font_style', models.CharField(blank=True, default='normal', max_length=32)),
                ('src', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('name', models.CharField(default='default', max_length=128, primary_key=True, serialize=False)),
                ('bg_main', models.CharField(default='#0A0A0A', max_length=128)),
                ('bg_nav', models.CharField(default='#121212', max_length=128)),
                ('bg_sidebar', models.CharField(default='#1A1A1A', max_length=128)),
                ('bg_sidebar_selection', models.CharField(default='#333333', max_length=128)),
                ('bg_sidebar_hover', models.CharField(default='#222222', max_length=128)),
                ('bg_content_blend', models.CharField(default='#0A0A0AC0', max_length=128)),
                ('bg_content', models.CharField(default='#0f0f0f', max_length=128)),
                ('text_color', models.CharField(default='#ffffff', max_length=128)),
                ('link_color', models.CharField(default='#cccccc', max_length=128)),
                ('accent_color', models.CharField(default='#ffa340', max_length=128)),
                ('secondary_color', models.CharField(default='#888888', max_length=128)),
                ('section_color', models.CharField(default='#eeeeee', max_length=128)),
                ('confirm_color', models.CharField(default='#dddddd', max_length=128)),
                ('bg_player_title', models.CharField(default='#2a2a2a', max_length=128)),
                ('shadow_color', models.CharField(default='#000000', max_length=128)),
                ('tile_placeholder', models.CharField(default='#333333', max_length=128)),
                ('tile_info', models.CharField(default='#050505', max_length=128)),
                ('tile_info_text', models.CharField(default='#666666', max_length=128)),
                ('gradient_begin', models.CharField(default='#444444', max_length=128)),
                ('gradient_end', models.CharField(default='#111111', max_length=128)),
                ('nav_height', models.CharField(default='60px', max_length=32)),
                ('sidebar_width', models.CharField(default='432px', max_length=32)),
                ('default_font', models.CharField(default="'lunchtype-regular'", max_length=32)),
                ('player_font', models.CharField(default="'lunchtype-regular'", max_length=32)),
                ('player_font_size', models.CharField(default='24px', max_length=32)),
                ('renderer', models.CharField(default='themed', max_length=32)),
                ('library_path', models.CharField(default='/src/melodify/D:\\/', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_friend', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.CharField(blank=True, max_length=300)),
                ('bio', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('genres', models.ManyToManyField(blank=True, to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('codename', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('brief', models.TextField(blank=True)),
                ('picture', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('booklet', models.FileField(blank=True, null=True, upload_to='booklets/')),
                ('edition', models.CharField(blank=True, default='Vanila', max_length=200)),
                ('limited', models.BooleanField(default=False)),
                ('release', models.DateField(blank=True, null=True)),
                ('artists', models.ManyToManyField(blank=True, to='main.artist')),
                ('genres', models.ManyToManyField(blank=True, to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='NostrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.CharField(help_text='Public key en formato hex', max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nostr_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=200)),
                ('filename', models.CharField(default='untitled.mp3', max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('track_number', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('lyrics', models.TextField(blank=True)),
                ('karaoke', models.TextField(blank=True)),
                ('picture', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('times_played', models.PositiveIntegerField(default=0)),
                ('times_skipped', models.PositiveIntegerField(default=0)),
                ('codename', models.CharField(blank=True, max_length=200)),
                ('error', models.BooleanField(default=False)),
                ('errors', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, default=1, null=True)),
                ('public', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=128)),
                ('bpm', models.FloatField(blank=True, null=True)),
                ('tone', models.CharField(blank=True, max_length=50)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.artist')),
                ('artists_and', models.ManyToManyField(blank=True, related_name='artists_and', to='main.artist')),
                ('artists_feat', models.ManyToManyField(blank=True, related_name='artists_feat', to='main.artist')),
                ('artists_prod', models.ManyToManyField(blank=True, related_name='artists_prod', to='main.artist')),
                ('artists_vs', models.ManyToManyField(blank=True, related_name='artists_vs', to='main.artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='main.genre')),
                ('genres', models.ManyToManyField(blank=True, related_name='genres', to='main.genre')),
                ('tags', models.ManyToManyField(blank=True, to='main.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='playlists/')),
                ('artists', models.ManyToManyField(blank=True, to='main.artist')),
                ('genres', models.ManyToManyField(blank=True, to='main.genre')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, to='main.song')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listens', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songstat_user', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songstat_song', to='main.song')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song')),
            ],
        ),
    ]
