# Generated by Django 6.0 on 2026-05-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='library_path',
            field=models.CharField(default='/library/', max_length=256),
        ),
    ]
